services:
  cinema_db:
    image: postgres:latest
    container_name: cinema_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cinema
      POSTGRES_DB: cinema
    ports:
      - "5432:5432"
    volumes:
      - cinema_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cinema"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.0-alpine
    container_name: cinema_redis
    ports:
      - "6379:6379"  
    volumes:
      - redis_data:/data
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: cinema_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - http.port=9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: cinema_kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    container_name: auth_service
    environment:
      - DB_HOST=cinema_db
      - DB_PORT=5432
      - DB_NAME=cinema
      - DB_USER=admin
      - DB_PASSWORD=cinema
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - KIBANA_HOST=kibana
      - KIBANA_PORT=5601
    ports:
      - "8000:8000"
    depends_on:
      cinema_db:
        condition: service_healthy
    restart: unless-stopped

  main_service:
    build:
      context: .
      dockerfile: main_service/Dockerfile
    container_name: main_service
    environment:
      - DB_HOST=cinema_db
      - DB_PORT=5432
      - DB_NAME=cinema
      - DB_USER=admin
      - DB_PASSWORD=cinema
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - KIBANA_HOST=kibana
      - KIBANA_PORT=5601
    ports:
      - "8001:8001"
    depends_on:
      cinema_db:
        condition: service_healthy
    restart: unless-stopped

  log_service:
    build:
      context: .
      dockerfile: log_service/Dockerfile
    container_name: log_service
    environment:
      - DB_HOST=cinema_db
      - DB_PORT=5432
      - DB_NAME=cinema
      - DB_USER=admin
      - DB_PASSWORD=cinema
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - KIBANA_HOST=kibana
      - KIBANA_PORT=5601
    ports:
      - "8002:8002"
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: unless-stopped

volumes:
  cinema_data:
  redis_data:
  elasticsearch_data: