"""Create all missing tables

Revision ID: 8e083a8cd90d
Revises: 001
Create Date: 2025-05-31 15:44:15.314220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e083a8cd90d'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.create_table('user_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    op.create_table('user_watchlist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    op.alter_column('movies', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('movies', 'duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('movies_tmdb_id_unique'), table_name='movies', postgresql_where='(tmdb_id IS NOT NULL)')
    op.drop_column('movies', 'tmdb_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('tmdb_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('movies_tmdb_id_unique'), 'movies', ['tmdb_id'], unique=True, postgresql_where='(tmdb_id IS NOT NULL)')
    op.alter_column('movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('movies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('movies', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('movies', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('user_watchlist')
    op.drop_table('user_favorites')
    op.drop_table('movie_genres')
    op.drop_table('users')
    op.drop_table('genres')
    # ### end Alembic commands ###
