"""Add tmdb_id to movies table

Revision ID: a8e2c49177c0
Revises: ad697f567373
Create Date: 2025-06-02 00:04:22.724572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e2c49177c0'
down_revision: Union[str, None] = 'ad697f567373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'movies', ['tmdb_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('movies', 'tmdb_id')
    # ### end Alembic commands ###
